## Introduction to Pandas: Data Manipulation

> It is often said that 80% of data analysis is spent on the data cleaning and preparing data. To get a handle on the problem, this section will focus on a small, nut important aspect of data manipulation and cleaning with pandas.

### Data Structures in Pandas

There are two different data structures are there in Pandas -
* **Series -** It is an one-dimensional labeled array of holding data of any data type (e.g. integer, string, floating point number, Python objects etc.). The axis are collectively referred to as the index.
* **Data Frame -** Is is a two-dimensional labeled data structure with columns of potentially different types. You can think of it as a SQL table or MS-Excel spreadsheets. 

### Series Data Structure

**pandas.core.series.Series(data, index, dtype, copy)**
* **data -** Data for the Series from list or ndarray or dictionary or constants etc.
* **index -** It is unique and hashable for easy identification
* **dtype -** It is for data type
* **copy -** It only affects Series on ndarray  data inputs

In [1]:
# importing required modules
import pandas as pd
import numpy as np

In [2]:
# creating empty Series
s = pd.Series()
print (s, len(s), type(s), id(s))

Series([], dtype: float64) 0 <class 'pandas.core.series.Series'> 1811469091792


<ipython-input-2-812467d8dfd0>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


In [5]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
print (type(s))

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
0     Amit
1    Kamal
2    Binay
3    Tuhin
dtype: object
<class 'pandas.core.series.Series'>


In [7]:
arr1 = np.array([100, 200, 300, 400, 500])
print(arr1)
s = pd.Series(data = arr1, copy = False)
print (s)
s[0] = 999
arr1[1] = 888
print (arr1)
print (s)

[100 200 300 400 500]
0    100
1    200
2    300
3    400
4    500
dtype: int32
[999 888 300 400 500]
0    999
1    888
2    300
3    400
4    500
dtype: int32


In [8]:
arr1 = np.array([100, 200, 300, 400, 500])
print(arr1)
s = pd.Series(data = arr1, copy = True)
print (s)
s[0] = 999
arr1[1] = 888
print (arr1)
print (s)

[100 200 300 400 500]
0    100
1    200
2    300
3    400
4    500
dtype: int32
[100 888 300 400 500]
0    999
1    200
2    300
3    400
4    500
dtype: int32


In [9]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
print (type(s))

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
0     Amit
1    Kamal
2    Binay
3    Tuhin
dtype: object
<class 'pandas.core.series.Series'>


In [11]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = [100, 101, 102, 103])
print (s)
print (type(s))
print (s[101], s[103])

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
100     Amit
101    Kamal
102    Binay
103    Tuhin
dtype: object
<class 'pandas.core.series.Series'>
Kamal Tuhin


In [13]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = [103, 101, 101, 103])
print (s)
print (type(s))
print (s[101])
print (s[103])

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
103     Amit
101    Kamal
101    Binay
103    Tuhin
dtype: object
<class 'pandas.core.series.Series'>
101    Kamal
101    Binay
dtype: object
103     Amit
103    Tuhin
dtype: object


In [17]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = ['1st', '2nd', '2nd', '3rd'])
print (s)
print (type(s))
print (s['1st'], type(s['1st']))
print (s['2nd'], type(s['2nd']))
print (s[0], s[2])

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
1st     Amit
2nd    Kamal
2nd    Binay
3rd    Tuhin
dtype: object
<class 'pandas.core.series.Series'>
Amit <class 'str'>
2nd    Kamal
2nd    Binay
dtype: object <class 'pandas.core.series.Series'>
Amit Binay


In [20]:
# creating Series from dictionary
my_data = {'a':100, 'b':300, 'c':700, 'd':900, 'e':450}
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
s = pd.Series(data = my_data, index = ['c', 'c', 'e', 'e', 'b', 'a', 'x'])
print (s)

{'a': 100, 'b': 300, 'c': 700, 'd': 900, 'e': 450} <class 'dict'>
a    100
b    300
c    700
d    900
e    450
dtype: int64
c    700.0
c    700.0
e    450.0
e    450.0
b    300.0
a    100.0
x      NaN
dtype: float64


In [22]:
# creating Series from a scalar or constant
s = pd.Series(5, index = [0, 1, 2, 3, 4])
print (s)
print (type(s))

0    5
1    5
2    5
3    5
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [26]:
# creating Series from a list
my_data = [11, 22, 33, 55, 44]
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = ['a', 'b', 'c', 'd', 'e'])
print (s)
print (type(s))
print (s['a'], type(s['a']))
print (s[0], type(s[0]))

[11, 22, 33, 55, 44] <class 'list'>
a    11
b    22
c    33
d    55
e    44
dtype: int64
<class 'pandas.core.series.Series'>
11 <class 'numpy.int64'>
11 <class 'numpy.int64'>
