## Introduction to Pandas: Data Manipulation

> It is often said that 80% of data analysis is spent on the data cleaning and preparing data. To get a handle on the problem, this section will focus on a small, nut important aspect of data manipulation and cleaning with pandas.

### Data Structures in Pandas

There are two different data structures are there in Pandas -
* **Series -** It is an one-dimensional labeled array of holding data of any data type (e.g. integer, string, floating point number, Python objects etc.). The axis are collectively referred to as the index.
* **Data Frame -** Is is a two-dimensional labeled data structure with columns of potentially different types. You can think of it as a SQL table or MS-Excel spreadsheets. 

### Series Data Structure

**pandas.core.series.Series(data, index, dtype, copy)**
* **data -** Data for the Series from list or ndarray or dictionary or constants etc.
* **index -** It is unique and hashable for easy identification
* **dtype -** It is for data type
* **copy -** It only affects Series on ndarray  data inputs

In [8]:
# importing required modules
import pandas as pd
import numpy as np

In [9]:
# creating empty Series
s = pd.Series()
print (s, len(s), type(s), id(s))

Series([], dtype: float64) 0 <class 'pandas.core.series.Series'> 1554901938288


<ipython-input-9-812467d8dfd0>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


In [10]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
print (type(s))

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
0     Amit
1    Kamal
2    Binay
3    Tuhin
dtype: object
<class 'pandas.core.series.Series'>


In [11]:
arr1 = np.array([100, 200, 300, 400, 500])
print(arr1)
s = pd.Series(data = arr1, copy = False)
print (s)
s[0] = 999
arr1[1] = 888
print (arr1)
print (s)

[100 200 300 400 500]
0    100
1    200
2    300
3    400
4    500
dtype: int32
[999 888 300 400 500]
0    999
1    888
2    300
3    400
4    500
dtype: int32


In [12]:
arr1 = np.array([100, 200, 300, 400, 500])
print(arr1)
s = pd.Series(data = arr1, copy = True)
print (s)
s[0] = 999
arr1[1] = 888
print (arr1)
print (s)

[100 200 300 400 500]
0    100
1    200
2    300
3    400
4    500
dtype: int32
[100 888 300 400 500]
0    999
1    200
2    300
3    400
4    500
dtype: int32


In [13]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
print (type(s))

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
0     Amit
1    Kamal
2    Binay
3    Tuhin
dtype: object
<class 'pandas.core.series.Series'>


In [14]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = [100, 101, 102, 103])
print (s)
print (type(s))
print (s[101], s[103])

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
100     Amit
101    Kamal
102    Binay
103    Tuhin
dtype: object
<class 'pandas.core.series.Series'>
Kamal Tuhin


In [15]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = [103, 101, 101, 103])
print (s)
print (type(s))
print (s[101])
print (s[103])

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
103     Amit
101    Kamal
101    Binay
103    Tuhin
dtype: object
<class 'pandas.core.series.Series'>
101    Kamal
101    Binay
dtype: object
103     Amit
103    Tuhin
dtype: object


In [16]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = ['1st', '2nd', '2nd', '3rd'])
print (s)
print (type(s))
print (s['1st'], type(s['1st']))
print (s['2nd'], type(s['2nd']))
print (s[0], s[2])

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
1st     Amit
2nd    Kamal
2nd    Binay
3rd    Tuhin
dtype: object
<class 'pandas.core.series.Series'>
Amit <class 'str'>
2nd    Kamal
2nd    Binay
dtype: object <class 'pandas.core.series.Series'>
Amit Binay


In [17]:
# creating Series from dictionary
my_data = {'a':100, 'b':300, 'c':700, 'd':900, 'e':450}
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
s = pd.Series(data = my_data, index = ['c', 'c', 'e', 'e', 'b', 'a', 'x'])
print (s)

{'a': 100, 'b': 300, 'c': 700, 'd': 900, 'e': 450} <class 'dict'>
a    100
b    300
c    700
d    900
e    450
dtype: int64
c    700.0
c    700.0
e    450.0
e    450.0
b    300.0
a    100.0
x      NaN
dtype: float64


In [18]:
# creating Series from a scalar or constant
s = pd.Series(5, index = [0, 1, 2, 3, 4])
print (s)
print (type(s))

0    5
1    5
2    5
3    5
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [19]:
# creating Series from a list
my_data = [11, 22, 33, 55, 44]
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = ['a', 'b', 'c', 'd', 'e'])
print (s)
print (type(s))
print (s['a'], type(s['a']))
print (s[0], type(s[0]))

[11, 22, 33, 55, 44] <class 'list'>
a    11
b    22
c    33
d    55
e    44
dtype: int64
<class 'pandas.core.series.Series'>
11 <class 'numpy.int64'>
11 <class 'numpy.int64'>


In [20]:
print (s)
print (s['a'], s[0]) # indexing
print (s['d'], s[3])
print (s[:3]) # slicing
print (s[2:])

a    11
b    22
c    33
d    55
e    44
dtype: int64
11 11
55 55
a    11
b    22
c    33
dtype: int64
c    33
d    55
e    44
dtype: int64


### Data Frame Data Structure

In [21]:
my_data = {'emp_name':['Amal', 'Kamal', ' Bimal'],
           'emp_age':[35, 45, 55]}
emp_id = [1001, 1002, 1003]
df = pd.DataFrame(data = my_data)
df

emp_name  emp_age
0     Amal       35
1    Kamal       45
2    Bimal       55

In [22]:
my_data = {'emp_name':['Amal', 'Kamal', ' Bimal'],
           'emp_age':[35, 45, 55]}
emp_id = [1001, 1002, 1003]
df = pd.DataFrame(data = my_data, index = emp_id)
df

emp_name  emp_age
1001     Amal       35
1002    Kamal       45
1003    Bimal       55

In [23]:
df = df.reset_index()
df

index emp_name  emp_age
0   1001     Amal       35
1   1002    Kamal       45
2   1003    Bimal       55

In [24]:
# converting data frame to ndarray
X = df[['emp_name', 'emp_age']]
print (X)
Y = X.to_numpy()
print (Y, type(Y))

  emp_name  emp_age
0     Amal       35
1    Kamal       45
2    Bimal       55
[['Amal' 35]
 ['Kamal' 45]
 [' Bimal' 55]] <class 'numpy.ndarray'>


In [25]:
var1 = 100
var2 = 200
print (var1)
print (var2)

100
200


In [26]:
my_columns = ['name', 'age', 'gender', 'job']
my_data = [['alice', 19, 'F', 'student'], ['john', 26, 'M', 'student']]
user1 = pd.DataFrame(data = my_data, columns = my_columns)
user1

name  age gender      job
0  alice   19      F  student
1   john   26      M  student

In [27]:
my_columns = ['name', 'age', 'gender', 'job']
my_data = [['eric', 22, 'M', 'student'], ['paul', 58, 'F', 'manager']]
user2 = pd.DataFrame(data = my_data, columns = my_columns)
user2

name  age gender      job
0  eric   22      M  student
1  paul   58      F  manager

In [28]:
my_dict = dict(name=['peter', 'julie'], age=[33, 44], gender=['M', 'F'], job=['engineer', 'scientist'])
print (my_dict, type(my_dict))
user3 = pd.DataFrame(data = my_dict)
user3

{'name': ['peter', 'julie'], 'age': [33, 44], 'gender': ['M', 'F'], 'job': ['engineer', 'scientist']} <class 'dict'>


name  age gender        job
0  peter   33      M   engineer
1  julie   44      F  scientist

### Concatenate Data Frame

In [29]:
df = user1.append(user2)
df

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
0   eric   22      M  student
1   paul   58      F  manager

In [30]:
df = user1.append(user2, ignore_index = True)
df

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student
3   paul   58      F  manager

In [31]:
df = user1.append(user2).append(user3, ignore_index = True)
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [32]:
users = pd.concat([user1, user2, user3])
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
0   eric   22      M    student
1   paul   58      F    manager
0  peter   33      M   engineer
1  julie   44      F  scientist

In [33]:
users = pd.concat([user1, user2, user3], ignore_index = True)
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

### Join Data Frame

In [34]:
my_dict = dict(name = ['alice', 'john', 'eric', 'julie', 'michel'],
               height = [165, 180, 175, 171, 185])
user4 = pd.DataFrame(data = my_dict)
user4

name  height
0   alice     165
1    john     180
2    eric     175
3   julie     171
4  michel     185

In [35]:
# inner join:  only common records
merge_inner = pd.merge(users, user4, on = "name", how = "inner")
merge_inner

name  age gender        job  height
0  alice   19      F    student     165
1   john   26      M    student     180
2   eric   22      M    student     175
3  julie   44      F  scientist     171

In [36]:
# inner join:  only common records
merge_inner = pd.merge(users, user4, on = "name")  # by default inner join
merge_inner

name  age gender        job  height
0  alice   19      F    student     165
1   john   26      M    student     180
2   eric   22      M    student     175
3  julie   44      F  scientist     171

In [37]:
# outer join:  all records from both tables
merge_outer = pd.merge(users, user4, on = "name", how = "outer")
merge_outer

name   age gender        job  height
0   alice  19.0      F    student   165.0
1    john  26.0      M    student   180.0
2    eric  22.0      M    student   175.0
3    paul  58.0      F    manager     NaN
4   peter  33.0      M   engineer     NaN
5   julie  44.0      F  scientist   171.0
6  michel   NaN    NaN        NaN   185.0

In [38]:
# left join:  all records from the left table and matching from the right table
merge_left = pd.merge(users, user4, on = "name", how = "left")
merge_left

name  age gender        job  height
0  alice   19      F    student   165.0
1   john   26      M    student   180.0
2   eric   22      M    student   175.0
3   paul   58      F    manager     NaN
4  peter   33      M   engineer     NaN
5  julie   44      F  scientist   171.0

In [39]:
# right join:  all records from the right table and matching from the left table
merge_right = pd.merge(users, user4, on = "name", how = "right")
merge_right

name   age gender        job  height
0   alice  19.0      F    student     165
1    john  26.0      M    student     180
2    eric  22.0      M    student     175
3   julie  44.0      F  scientist     171
4  michel   NaN    NaN        NaN     185

### Summarizing

In [40]:
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [41]:
print (type(users))
users.head()

<class 'pandas.core.frame.DataFrame'>


name  age gender       job
0  alice   19      F   student
1   john   26      M   student
2   eric   22      M   student
3   paul   58      F   manager
4  peter   33      M  engineer

In [42]:
users.head(3)

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student

In [43]:
users.tail()

name  age gender        job
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [44]:
users.tail(3)

name  age gender        job
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [45]:
users.sample()

name  age gender      job
1  john   26      M  student

In [46]:
users.sample(3)

name  age gender        job
5  julie   44      F  scientist
2   eric   22      M    student
4  peter   33      M   engineer

In [47]:
users.describe()

age
count   6.000000
mean   33.666667
std    14.895189
min    19.000000
25%    23.000000
50%    29.500000
75%    41.250000
max    58.000000

In [48]:
users.describe(include = 'all')

name        age gender      job
count      6   6.000000      6        6
unique     6        NaN      2        4
top     john        NaN      M  student
freq       1        NaN      3        3
mean     NaN  33.666667    NaN      NaN
std      NaN  14.895189    NaN      NaN
min      NaN  19.000000    NaN      NaN
25%      NaN  23.000000    NaN      NaN
50%      NaN  29.500000    NaN      NaN
75%      NaN  41.250000    NaN      NaN
max      NaN  58.000000    NaN      NaN

In [49]:
users.describe(include = ['object'])

name gender      job
count      6      6        6
unique     6      2        4
top     john      M  student
freq       1      3        3

In [50]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    6 non-null      object
 1   age     6 non-null      int64 
 2   gender  6 non-null      object
 3   job     6 non-null      object
dtypes: int64(1), object(3)
memory usage: 320.0+ bytes


In [63]:
print (df.shape, df.shape[0], df.shape[1])
print (len(df))
print (df.ndim)
print (df.size)

(6, 4) 6 4
6
2
24


### Columns Selection

In [53]:
print (users['gender'])
print (type(users['gender']))

0    F
1    M
2    M
3    F
4    M
5    F
Name: gender, dtype: object
<class 'pandas.core.series.Series'>


In [55]:
print (type(users[['gender', 'age', 'name']]))
users[['gender', 'age', 'name']]

<class 'pandas.core.frame.DataFrame'>


gender  age   name
0      F   19  alice
1      M   26   john
2      M   22   eric
3      F   58   paul
4      M   33  peter
5      F   44  julie

In [57]:
my_cols = ['gender', 'age', 'name']
print (type(users[my_cols]))
users[my_cols]

<class 'pandas.core.frame.DataFrame'>


gender  age   name
0      F   19  alice
1      M   26   john
2      M   22   eric
3      F   58   paul
4      M   33  peter
5      F   44  julie

### Rows Selection

In [64]:
df = users.copy()
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [67]:
print (df.iloc[0])
print ()
print (df.loc[0])

name        alice
age            19
gender          F
job       student
Name: 0, dtype: object

name        alice
age            19
gender          F
job       student
Name: 0, dtype: object


In [68]:
print (df.iloc[3])
print ()
print (df.loc[3])

name         paul
age            58
gender          F
job       manager
Name: 3, dtype: object

name         paul
age            58
gender          F
job       manager
Name: 3, dtype: object


In [69]:
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [81]:
print (df.iloc[4][3], df.iloc[4]['job'], df.loc[4][3], df.loc[4]['job'])
print (df.iloc[4, 3], df.iloc[4]['job'], df.loc[4][3], df.loc[4, 'job'])

engineer engineer engineer engineer
engineer engineer engineer engineer


In [91]:
df = users.copy()
for i in range(df.shape[0]):
    row = df.iloc[i]
    # print (row)
    # print (row.age)
    row.age += 100
    # print (row.age)
    df.iloc[i] = row
df

C:\Users\Arnab\anaconda3\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


name  age gender        job
0  alice  119      F    student
1   john  126      M    student
2   eric  122      M    student
3   paul  158      F    manager
4  peter  133      M   engineer
5  julie  144      F  scientist

### Rows Selection and Filtering

In [94]:
# simple logical filtering
print (users.age < 30)
users[users.age < 30]

0     True
1     True
2     True
3    False
4    False
5    False
Name: age, dtype: bool


name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student

In [96]:
bool_age = users.age < 30
print (bool_age)
users[bool_age]

0     True
1     True
2     True
3    False
4    False
5    False
Name: age, dtype: bool


name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student

In [98]:
users[bool_age].age

0    19
1    26
2    22
Name: age, dtype: int64

In [99]:
users[bool_age]['age']

0    19
1    26
2    22
Name: age, dtype: int64

In [103]:
users[bool_age][['age', 'name']]

age   name
0   19  alice
1   26   john
2   22   eric

In [104]:
bool_age = (users.age >= 30) & (users.age <= 50)
print (bool_age)
users[bool_age][['age', 'name']]

0    False
1    False
2    False
3    False
4     True
5     True
Name: age, dtype: bool


age   name
4   33  peter
5   44  julie

In [105]:
bool_age = (users.age > 30) & (users.gender == "M")
print (bool_age)
users[bool_age][['age', 'name','gender']]

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool


age   name gender
4   33  peter      M

In [106]:
users[users.job.isin(['student', 'engineer'])]

name  age gender       job
0  alice   19      F   student
1   john   26      M   student
2   eric   22      M   student
4  peter   33      M  engineer

### Sorting

In [107]:
df = users.copy()
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [109]:
df.age.sort_values()

0    19
2    22
1    26
4    33
5    44
3    58
Name: age, dtype: int64

In [111]:
df.age.sort_values(ascending = True)

0    19
2    22
1    26
4    33
5    44
3    58
Name: age, dtype: int64

In [112]:
df.age.sort_values(ascending = False)

3    58
5    44
4    33
1    26
2    22
0    19
Name: age, dtype: int64

In [118]:
df.sort_values(by = 'age', ascending = False, inplace = True, ignore_index = True)

In [119]:
df

name  age gender        job
0   paul   58      F    manager
1  julie   44      F  scientist
2  peter   33      M   engineer
3   john   26      M    student
4   eric   22      M    student
5  alice   19      F    student