## Introduction to Pandas: Data Manipulation

> It is often said that 80% of data analysis is spent on the data cleaning and preparing data. To get a handle on the problem, this section will focus on a small, nut important aspect of data manipulation and cleaning with pandas.

### Data Structures in Pandas

There are two different data structures are there in Pandas -
* **Series -** It is an one-dimensional labeled array of holding data of any data type (e.g. integer, string, floating point number, Python objects etc.). The axis are collectively referred to as the index.
* **Data Frame -** Is is a two-dimensional labeled data structure with columns of potentially different types. You can think of it as a SQL table or MS-Excel spreadsheets. 

### Series Data Structure

**pandas.core.series.Series(data, index, dtype, copy)**
* **data -** Data for the Series from list or ndarray or dictionary or constants etc.
* **index -** It is unique and hashable for easy identification
* **dtype -** It is for data type
* **copy -** It only affects Series on ndarray  data inputs

In [1]:
# importing required modules
import pandas as pd
import numpy as np

In [2]:
# creating empty Series
s = pd.Series()
print (s, len(s), type(s), id(s))

Series([], dtype: float64) 0 <class 'pandas.core.series.Series'> 1811469091792


<ipython-input-2-812467d8dfd0>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


In [5]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
print (type(s))

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
0     Amit
1    Kamal
2    Binay
3    Tuhin
dtype: object
<class 'pandas.core.series.Series'>


In [7]:
arr1 = np.array([100, 200, 300, 400, 500])
print(arr1)
s = pd.Series(data = arr1, copy = False)
print (s)
s[0] = 999
arr1[1] = 888
print (arr1)
print (s)

[100 200 300 400 500]
0    100
1    200
2    300
3    400
4    500
dtype: int32
[999 888 300 400 500]
0    999
1    888
2    300
3    400
4    500
dtype: int32


In [8]:
arr1 = np.array([100, 200, 300, 400, 500])
print(arr1)
s = pd.Series(data = arr1, copy = True)
print (s)
s[0] = 999
arr1[1] = 888
print (arr1)
print (s)

[100 200 300 400 500]
0    100
1    200
2    300
3    400
4    500
dtype: int32
[100 888 300 400 500]
0    999
1    200
2    300
3    400
4    500
dtype: int32


In [9]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
print (type(s))

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
0     Amit
1    Kamal
2    Binay
3    Tuhin
dtype: object
<class 'pandas.core.series.Series'>


In [11]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = [100, 101, 102, 103])
print (s)
print (type(s))
print (s[101], s[103])

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
100     Amit
101    Kamal
102    Binay
103    Tuhin
dtype: object
<class 'pandas.core.series.Series'>
Kamal Tuhin


In [13]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = [103, 101, 101, 103])
print (s)
print (type(s))
print (s[101])
print (s[103])

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
103     Amit
101    Kamal
101    Binay
103    Tuhin
dtype: object
<class 'pandas.core.series.Series'>
101    Kamal
101    Binay
dtype: object
103     Amit
103    Tuhin
dtype: object


In [17]:
# creating Series from ndarray
my_data = np.array(['Amit', 'Kamal', 'Binay', 'Tuhin'])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = ['1st', '2nd', '2nd', '3rd'])
print (s)
print (type(s))
print (s['1st'], type(s['1st']))
print (s['2nd'], type(s['2nd']))
print (s[0], s[2])

['Amit' 'Kamal' 'Binay' 'Tuhin'] <class 'numpy.ndarray'>
1st     Amit
2nd    Kamal
2nd    Binay
3rd    Tuhin
dtype: object
<class 'pandas.core.series.Series'>
Amit <class 'str'>
2nd    Kamal
2nd    Binay
dtype: object <class 'pandas.core.series.Series'>
Amit Binay


In [20]:
# creating Series from dictionary
my_data = {'a':100, 'b':300, 'c':700, 'd':900, 'e':450}
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
s = pd.Series(data = my_data, index = ['c', 'c', 'e', 'e', 'b', 'a', 'x'])
print (s)

{'a': 100, 'b': 300, 'c': 700, 'd': 900, 'e': 450} <class 'dict'>
a    100
b    300
c    700
d    900
e    450
dtype: int64
c    700.0
c    700.0
e    450.0
e    450.0
b    300.0
a    100.0
x      NaN
dtype: float64


In [22]:
# creating Series from a scalar or constant
s = pd.Series(5, index = [0, 1, 2, 3, 4])
print (s)
print (type(s))

0    5
1    5
2    5
3    5
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [26]:
# creating Series from a list
my_data = [11, 22, 33, 55, 44]
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = ['a', 'b', 'c', 'd', 'e'])
print (s)
print (type(s))
print (s['a'], type(s['a']))
print (s[0], type(s[0]))

[11, 22, 33, 55, 44] <class 'list'>
a    11
b    22
c    33
d    55
e    44
dtype: int64
<class 'pandas.core.series.Series'>
11 <class 'numpy.int64'>
11 <class 'numpy.int64'>


In [31]:
print (s)
print (s['a'], s[0]) # indexing
print (s['d'], s[3])
print (s[:3]) # slicing
print (s[2:])

a    11
b    22
c    33
d    55
e    44
dtype: int64
11 11
55 55
a    11
b    22
c    33
dtype: int64
c    33
d    55
e    44
dtype: int64


### Data Frame Data Structure

In [33]:
my_data = {'emp_name':['Amal', 'Kamal', ' Bimal'],
           'emp_age':[35, 45, 55]}
emp_id = [1001, 1002, 1003]
df = pd.DataFrame(data = my_data)
df

emp_name  emp_age
0     Amal       35
1    Kamal       45
2    Bimal       55

In [34]:
my_data = {'emp_name':['Amal', 'Kamal', ' Bimal'],
           'emp_age':[35, 45, 55]}
emp_id = [1001, 1002, 1003]
df = pd.DataFrame(data = my_data, index = emp_id)
df

emp_name  emp_age
1001     Amal       35
1002    Kamal       45
1003    Bimal       55

In [36]:
df = df.reset_index()
df

index emp_name  emp_age
0   1001     Amal       35
1   1002    Kamal       45
2   1003    Bimal       55

In [39]:
# converting data frame to ndarray
X = df[['emp_name', 'emp_age']]
print (X)
Y = X.to_numpy()
print (Y, type(Y))

  emp_name  emp_age
0     Amal       35
1    Kamal       45
2    Bimal       55
[['Amal' 35]
 ['Kamal' 45]
 [' Bimal' 55]] <class 'numpy.ndarray'>


In [43]:
var1 = 100
var2 = 200
print (var1)
print (var2)

100
200


In [67]:
my_columns = ['name', 'age', 'gender', 'job']
my_data = [['alice', 19, 'F', 'student'], ['john', 26, 'M', 'student']]
user1 = pd.DataFrame(data = my_data, columns = my_columns)
user1

name  age gender      job
0  alice   19      F  student
1   john   26      M  student

In [68]:
my_columns = ['name', 'age', 'gender', 'job']
my_data = [['eric', 22, 'M', 'student'], ['paul', 58, 'F', 'manager']]
user2 = pd.DataFrame(data = my_data, columns = my_columns)
user2

name  age gender      job
0  eric   22      M  student
1  paul   58      F  manager

In [69]:
my_dict = dict(name=['peter', 'julie'], age=[33, 44], gender=['M', 'F'], job=['engineer', 'scientist'])
print (my_dict, type(my_dict))
user3 = pd.DataFrame(data = my_dict)
user3

{'name': ['peter', 'julie'], 'age': [33, 44], 'gender': ['M', 'F'], 'job': ['engineer', 'scientist']} <class 'dict'>


name  age gender        job
0  peter   33      M   engineer
1  julie   44      F  scientist

### Concatenate Data Frame

In [70]:
df = user1.append(user2)
df

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
0   eric   22      M  student
1   paul   58      F  manager

In [71]:
df = user1.append(user2, ignore_index = True)
df

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student
3   paul   58      F  manager

In [72]:
df = user1.append(user2).append(user3, ignore_index = True)
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [73]:
users = pd.concat([user1, user2, user3])
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
0   eric   22      M    student
1   paul   58      F    manager
0  peter   33      M   engineer
1  julie   44      F  scientist

In [74]:
users = pd.concat([user1, user2, user3], ignore_index = True)
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

### Join Data Frame

In [77]:
my_dict = dict(name = ['alice', 'john', 'eric', 'julie', 'michel'],
               height = [165, 180, 175, 171, 185])
user4 = pd.DataFrame(data = my_dict)
user4

name  height
0   alice     165
1    john     180
2    eric     175
3   julie     171
4  michel     185

In [79]:
# inner join:  only common records
merge_inner = pd.merge(users, user4, on = "name", how = "inner")
merge_inner

name  age gender        job  height
0  alice   19      F    student     165
1   john   26      M    student     180
2   eric   22      M    student     175
3  julie   44      F  scientist     171

In [81]:
# inner join:  only common records
merge_inner = pd.merge(users, user4, on = "name")  # by default inner join
merge_inner

name  age gender        job  height
0  alice   19      F    student     165
1   john   26      M    student     180
2   eric   22      M    student     175
3  julie   44      F  scientist     171

In [83]:
# outer join:  all records from both tables
merge_outer = pd.merge(users, user4, on = "name", how = "outer")
merge_outer

name   age gender        job  height
0   alice  19.0      F    student   165.0
1    john  26.0      M    student   180.0
2    eric  22.0      M    student   175.0
3    paul  58.0      F    manager     NaN
4   peter  33.0      M   engineer     NaN
5   julie  44.0      F  scientist   171.0
6  michel   NaN    NaN        NaN   185.0